version: '3.8'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: admin
      MYSQL_PASSWORD: masterkey
      MYSQL_DATABASE: dbsCeps
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  # app:
  #   build: .
  #   container_name: app_container
  #   depends_on:
  #     - mysql
  #   ports:
  #     - "8082:8082"
  #   environment:
  #     DB_HOST: mysql
  #     DB_PORT: 3306
  #     DB_USER: usuario
  #     DB_PASSWORD: senha
  #     DB_NAME: meubanco

volumes:
  mysql_data:
    driver: local


# docker compose up -d