version: '3.8'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: admin
      MYSQL_PASSWORD: masterkey
      MYSQL_DATABASE: dbsCeps
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command:
      --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci  

volumes:
  mysql_data:
    driver: local

# comando para rodar o docker compose
# docker-compose up -d    
