FROM ubuntu:18.04

RUN apt update -y && apt upgrade -y && apt dist-upgrade -y
RUN apt install -y joe wget p7zip-full curl openssh-server build-essential zlib1g-dev libcurl4-gnutls-dev libncurses5

COPY ./LinuxPAServer22.0.tar.gz ./

RUN apt-get install -y zlib1g-dev

RUN tar -xvf ./LinuxPAServer22.0.tar.gz

ENTRYPOINT  ./PAServer-22.0/paserver -password=

# docker build -t delphi/paserver .
# docker run -p 64211:64211 -d delphi/paserver
